#!/bin/bash

CONFIG_FILE="$HOME/.pi-switcher/git-config.json"
SSH_CONFIG="$HOME/.ssh/config"
BACKUP="$SSH_CONFIG.bak.$(date +%Y%m%d%H%M%S)"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ Git config not found: $CONFIG_FILE"
  exit 1
fi

echo "🔧 Syncing ~/.ssh/config from git-config.json..."

# Backup existing .ssh/config
if [ -f "$SSH_CONFIG" ]; then
  cp "$SSH_CONFIG" "$BACKUP"
  echo "📦 Backup created: $BACKUP"
fi

# Start fresh
echo "# Auto-generated by pi-switcher" > "$SSH_CONFIG"

# Load keys from config
jq -r '
  .ssh_keys | to_entries[] |
  "Host github-\(.key)\n  HostName github.com\n  User git\n  IdentityFile \(.value.path)\n"
' "$CONFIG_FILE" >> "$SSH_CONFIG"

echo "✅ ~/.ssh/config updated."
